# Generated by Django 2.1.4 on 2018-12-30 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='number',
            field=models.CharField(default='001', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trolleys',
            field=models.CharField(default='1111', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='SA132', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty',
            field=models.DateField(default=datetime.date(2018, 2, 1)),
            preserve_default=False,
        ),
    ]
