# Generated by Django 2.1.4 on 2018-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181230_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='trolleys',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
