# Generated by Django 2.1.4 on 2018-12-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20181231_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('P1.1', 'P1.1'), ('P1.2', 'P1.2'), ('P1.3', 'P1.3'), ('P2.1', 'P2.1'), ('P2.2', 'P2.2'), ('P2.3', 'P2.3'), ('P3.1', 'P3.1'), ('P3.2', 'P3.2')], db_index=True, max_length=10, null=True),
        ),
    ]
