# Generated by Django 2.1.4 on 2018-12-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181231_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SA132', 'SA132'), ('SA134', 'SA134'), ('SA139', 'SA139')], db_index=True, max_length=10),
        ),
    ]
