# Generated by Django 2.1.4 on 2018-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20181231_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
