# Generated by Django 2.1.4 on 2019-01-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20181231_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='actions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='category',
            field=models.CharField(choices=[('pudło', (('nadwozie', 'Nadwozie'), ('poszycie', 'Poszycie'), ('podłoga', 'Podłoga'), ('konstrukcja', 'Konstrukcja'), ('układy nośne', 'Układy nośne'), ('grodzenia', 'Grodzenia'))), ('materiały wykończeniowe', (('malatura', 'Malatura'), ('kalkomania', 'Kalkomania'))), ('wyposażnie wewn.', 'Wyposażenie wewnętrzne'), ('wózek', 'Wózek'), ('urządz. ster. pojazdem', 'Urządzenia sterujące pojazdem'), ('urządz, monitoringu i bezpiecz.', 'Urządzenia monitoringu i bezpieczeństwa'), ('klima i orzewanie', 'Klimatyzacja i ogrzewanie'), ('drzwi', 'Drzwi'), ('sip', 'Urządzenia informacyjne'), ('układ hamowania', 'Układ hamowania'), ('układ sprzęgania', 'Układ sprzęgania'), ('okna i szyby', 'Okna i szyby'), ('układ elek.', 'Układ elektryczny'), ('Układ napędowy', (('silnik', 'Silnik'), ('przekładnia', 'Przekładnia'))), ('Wyposażenie zewnętrzne', (('wycieraczki', 'Wycieraczki'), ('lusterka', 'Lusterka'), ('syreny', 'Syreny'))), ('układ pneumatyczny', 'Układ pneumatyczny')], db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='complaint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complaint_faults', to='book.Complaint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fault',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_faults', to='book.Vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='zr_number',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
