# Generated by Django 2.1.4 on 2019-01-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20190101_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('index', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('recovered', 'Recovered')], db_index=True, max_length=10)),
                ('assembly_date', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='fault',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='fault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='book.Fault'),
        ),
    ]
