# Generated by Django 2.1.4 on 2019-01-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20190101_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='origin',
            field=models.CharField(choices=[('pesa', 'Pesa'), ('kw', 'Koleje Wielkopolskie')], db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
