# Generated by Django 2.1.4 on 2019-01-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_part_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateField(default='2018-04-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('P1.1', 'P1.1'), ('P1.2', 'P1.2'), ('P1.3', 'P1.3'), ('P2.1', 'P2.1'), ('P2.2', 'P2.2'), ('P2.3', 'P2.3'), ('P3.1', 'P3.1'), ('P3.2', 'P3.2')], db_index=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='performer',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='book.Vehicle'),
            preserve_default=False,
        ),
    ]
