# Generated by Django 2.1.4 on 2019-01-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_change_inspection_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='assembly_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
