# Generated by Django 2.1.4 on 2019-01-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_add_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_complaint', to='book.Owner'),
        ),
    ]
