# Generated by Django 2.1.4 on 2019-01-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_change_model_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='book.Owner'),
            preserve_default=False,
        ),
    ]
