# Generated by Django 2.1.4 on 2019-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_add_owner_field_to_model_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
