# Generated by Django 2.1.4 on 2019-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_add_uniqe_to_name_model_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='slug',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
