# Generated by Django 2.1.4 on 2019-01-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_add_slug_to_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='slug',
            field=models.CharField(max_length=20),
        ),
    ]
