# Generated by Django 2.1.4 on 2019-01-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_remove_unique_from_slug_in_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolleys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20, unique=True)),
                ('second', models.CharField(max_length=20, unique=True)),
                ('third', models.CharField(blank=True, max_length=20, unique=True)),
                ('fourth', models.CharField(blank=True, max_length=20, unique=True)),
                ('fifth', models.CharField(blank=True, max_length=20, unique=True)),
                ('sixth', models.CharField(blank=True, max_length=20, unique=True)),
                ('seventh', models.CharField(blank=True, max_length=20, unique=True)),
                ('eighth', models.CharField(blank=True, max_length=20, unique=True)),
                ('ninth', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trolleys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trolleys', to='book.Trolleys'),
        ),
    ]
