# Generated by Django 2.1.4 on 2019-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_added_model_Trollyes_and_alter_filed_trolleys_in_Vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolleys',
            name='third',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
