# Generated by Django 2.1.4 on 2019-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20190106_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolleys',
            name='eighth',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trolleys',
            name='fifth',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trolleys',
            name='fourth',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trolleys',
            name='ninth',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trolleys',
            name='seventh',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trolleys',
            name='sixth',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
