# Generated by Django 2.1.4 on 2019-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_add_null_to_fields_in_trolleys'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolleys',
            name='name',
            field=models.CharField(choices=[('SA132', 'SA132'), ('SA134', 'SA134'), ('SA139', 'SA139')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
