# Generated by Django 2.1.4 on 2019-01-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_add_name_to_trolleys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolleys',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trolleys',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trolleys', to='book.Trolleys'),
        ),
    ]
