# Generated by Django 2.1.4 on 2019-01-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_alter_trolleys_in_vehicle_to_one_to_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='fault',
            name='zr_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
