# Generated by Django 2.1.4 on 2019-01-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_add_null_to_zr_number_model_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
    ]
