# Generated by Django 2.1.4 on 2019-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_removed_field_user_from_model_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
