# Generated by Django 2.1.4 on 2019-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_added_field_entry_date_to_fault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ('entry_date',)},
        ),
        migrations.AddField(
            model_name='fault',
            name='moved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fault',
            name='need',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
