# Generated by Django 2.1.4 on 2019-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_added_two_fileds_in_model_fault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='need',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SA132', 'SA132'), ('SA133', 'SA133'), ('SA134', 'SA134'), ('SA139', 'SA139')], db_index=True, max_length=10),
        ),
    ]
