# Generated by Django 2.1.4 on 2019-01-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_added_blank_to_field_need_in_fault'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('vehicle_type', 'number')},
        ),
        migrations.RemoveField(
            model_name='fault',
            name='moved_date',
        ),
    ]
