# Generated by Django 2.1.4 on 2019-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_removed_field_move_to_in_fault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
