# Generated by Django 2.2.13 on 2020-06-29 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0037_add_unique_to_document_number_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_complaint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 6, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarta'), ('close', 'Zamknięta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fault',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarta'), ('close', 'Zamknięta')], max_length=10),
        ),
    ]
