# Generated by Django 2.2.13 on 2020-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_added_auth_and_publish_date_to_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
