# Generated by Django 2.2.13 on 2020-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_changed_datefield_to_datetimeField_in_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
