# Generated by Django 2.2.13 on 2020-07-05 15:22

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_changed_fault_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=book.models.user_directory_path),
        ),
    ]
