# Generated by Django 2.2.13 on 2020-07-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_added_new_model_for_multiple_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file_document',
        ),
    ]
