# Generated by Django 2.2.13 on 2020-07-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0042_changed_name_file_to_file_document_in_File_model'),
        ('book', '0041_added_file_field_to_complaint'),
    ]

    operations = [
    ]
