# Generated by Django 2.2.13 on 2020-07-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0043_merge_20200706_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='file',
        ),
    ]
