# Generated by Django 2.2.13 on 2020-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0044_remove_complaint_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('SA132', 'SA132'), ('SA133', 'SA133'), ('SA134', 'SA134'), ('SA136', 'SA136'), ('SA139', 'SA139')], db_index=True, max_length=10),
        ),
    ]
