# Generated by Django 2.2.13 on 2020-07-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0046_added_new_model_fault_without_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-entry_date',)},
        ),
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ('-entry_date',)},
        ),
        migrations.AlterModelOptions(
            name='fault_without_complaint',
            options={'ordering': ('-entry_date',)},
        ),
    ]
